### PR TITLE
Updating the articles along with the actual pdfs

### PR DESCRIPTION
**Pull request by kibet-gilbert**
The folder "openscienceke-updatedjournal-reference" contain 1.1Gb of files and reference documents of 101 articles, thesis and books.

### CODE REVIEW

**Comment by kipkurui** [comment]
Hi @kibet-gilbert , that is a huge commit. How many files are they, and are they all open access?

**Comment by kibet-gilbert** [comment]
They are in total 101(books, articles and theses). The actual reference file (.bib) is 673kb.
The majority of the files (found in "openscienceke-updatedjournal-reference/files") are among others pdfs and other descriptive files generated by zotero.
The articles are not all open access and i have not included them. The only ones included yet not open access are those accessible from icipe that include onlinelibrary.wiley.com.

**Comment by kibet-gilbert** [comment]
Let me work a little more on them then resend a pull request

**Comment by kibet-gilbert** [comment]
updated version coming

**Pull request closed without merging**
